version: '3.9'

networks:
  app-network-microservice:
    external: true

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-product
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db_tubes_product
    networks:
      app-network-microservice:
        aliases:
          - mysql-product
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis-product
    networks:
      app-network-microservice:
        aliases:
          - redis-product

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-product
    environment:
      PMA_HOST: mysql-product
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - app-network-microservice
    ports:
      - "8083:80"

  service-product:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service-product
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MYSQL_HOST: mysql-product
      MYSQL_PORT: 3306
      MYSQL_DATABASE: db_tubes_product
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 12345
      REDIS_HOST: redis-product
      REDIS_PORT: 6379
      SERVER_PORT: 9003
      LOG_LEVEL_CACHE: DEBUG
      LOG_LEVEL: DEBUG
      LOG_LEVEL_WEB: DEBUG
    networks:
      - app-network-microservice
    restart: on-failure
